spring.datasource.jdbc-url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

spring.authdatasource.jdbc-url=${SPRING_AUTHDATASOURCE_URL}
spring.authdatasource.username=${SPRING_AUTHDATASOURCE_USERNAME}
spring.authdatasource.password=${SPRING_AUTHDATASOURCE_PASSWORD}
spring.authdatasource.driverClassName=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=*
info.app.name=Arcane Market
info.app.java.version=${java.version}
management.info.env.enabled=true
management.endpoint.health.show-details=always

spring.redis.host=redis
spring.redis.port=6379