spring.datasource.jdbc-url=jdbc:postgresql://16.171.254.158:5432/apidb
spring.datasource.username=postgres
spring.datasource.password=superhaslo
spring.datasource.driverClassName=org.postgresql.Driver

spring.authdatasource.jdbc-url=jdbc:postgresql://16.171.254.158:5433/authdb
spring.authdatasource.username=postgres
spring.authdatasource.password=superhaslo
spring.authdatasource.driverClassName=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=haslo123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=spring-ssl

spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=*
info.app.name=Arcane Market
info.app.java.version=${java.version}
management.info.env.enabled=true
management.endpoint.health.show-details=always

grpc.server.port=9090