INSERT INTO items (name, rarity, type, min_level) VALUES
('Runiczny Miecz', 'RARE', 'sword', 20),
('Zbroja Cienia', 'EPIC', 'armor', 25),
('Kostur Arcymaga', 'LEGENDARY', 'accessory', 45),
('Hełm Strażnika', 'COMMON', 'armor', 22),
('Buty Szybkości', 'RARE', 'armor', 20),
('Tarcza Smoczej Łuski', 'EPIC', 'shield', 35),
('Pierścień Mocy', 'LEGENDARY', 'accessory', 50),
('Amulet Życia', 'RARE', 'accessory', 28),
('Rękawice Złodzieja', 'COMMON', 'armor', 21),
('Topór Wojownika', 'RARE', 'sword', 24),
('Peleryna Niewidzialności', 'EPIC', 'armor', 40),
('Łuk Elfi', 'RARE', 'sword', 30),
('Sztylet Trucizny', 'COMMON', 'sword', 23),
('Naszyjnik Mądrości', 'RARE', 'accessory', 26),
('Karwasze Ognia', 'EPIC', 'armor', 8),
('Pas Siły', 'RARE', 'armor', 22),
('Klejnot Duszy', 'LEGENDARY', 'potion', 55),
('Maska Upiora', 'EPIC', 'armor', 42),
('Laska Uzdrowiciela', 'RARE', 'potion', 29),
('Zbroja Płytowa', 'COMMON', 'armor', 32);