INSERT INTO items (name, rarity, type, min_level) VALUES
('Runiczny Miecz', 'RARE', 'weapon', 20),
('Zbroja Cienia', 'EPIC', 'armor', 25),
('Kostur Arcymaga', 'LEGENDARY', 'accessory', 45),
('Hełm Strażnika', 'COMMON', 'armor', 22),
('Buty Szybkości', 'RARE', 'armor', 20),
('Tarcza Smoczej Łuski', 'EPIC', 'shield', 35),
('Pierścień Mocy', 'LEGENDARY', 'accessory', 50),
('Amulet Życia', 'RARE', 'potion', 28),
('Rękawice Złodzieja', 'COMMON', 'armor', 21),
('Topór Wojownika', 'RARE', 'weapon', 24),
('Peleryna Niewidzialności', 'EPIC', 'armor', 40),
('Łuk Elfi', 'RARE', 'weapon', 30),
('Sztylet Trucizny', 'COMMON', 'weapon', 23),
('Naszyjnik Mądrości', 'RARE', 'accessory', 26),
('Karwasze Ognia', 'EPIC', 'armor', 8),
('Pas Siły', 'RARE', 'armor', 22),
('Klejnot Duszy', 'LEGENDARY', 'potion', 55),
('Maska Upiora', 'EPIC', 'armor', 42),
('Laska Uzdrowiciela', 'RARE', 'potion', 29),
('Zbroja Płytowa', 'COMMON', 'armor', 32),
('Miecz Stali', 'COMMON', 'weapon', 5),
('Tarcza Drewniana', 'COMMON', 'shield', 5),
('Mikstura Many', 'COMMON', 'potion', 10),
('Kula Ognia', 'RARE', 'accessory', 15),
('Tarcza Królewska', 'LEGENDARY', 'shield', 50),
('Błyskawica', 'EPIC', 'accessory', 30),
('Szata Maga', 'UNCOMMON', 'armor', 15),
('Mikstura Leczenia', 'COMMON', 'potion', 1),
('Tarcza Żelazna', 'UNCOMMON', 'shield', 12),
('Miecz Ognia', 'EPIC', 'weapon', 35);