
DROP TABLE IF EXISTS auction_history CASCADE;
DROP TABLE IF EXISTS auctions CASCADE;
DROP TABLE IF EXISTS items_user CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    wallet REAL NOT NULL DEFAULT 0.0,
    avatar_content_type VARCHAR(50),
    avatar BYTEA
);


CREATE TABLE IF NOT EXISTS items (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    rarity VARCHAR(255),
    type VARCHAR(50),
    min_level INT
);


CREATE TABLE IF NOT EXISTS items_user (
    unique_item_id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    on_auction BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_iu_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_iu_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS auctions (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    time_duration INT NOT NULL,
    creation_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    price REAL NOT NULL
);


CREATE TABLE IF NOT EXISTS auction_history (
    id BIGSERIAL PRIMARY KEY,
    auction_id BIGINT NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL
);


ALTER TABLE auctions ADD CONSTRAINT fk_auctions_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE;
ALTER TABLE auction_history ADD CONSTRAINT fk_history_auction FOREIGN KEY (auction_id) REFERENCES auctions(id) ON DELETE CASCADE;
ALTER TABLE auction_history ADD CONSTRAINT fk_history_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE auctions ADD CONSTRAINT fk_auctions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;