// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: rpg_system.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RpgService_GetInventory_FullMethodName            = "/rpg.RpgService/GetInventory"
	RpgService_GetAuctions_FullMethodName             = "/rpg.RpgService/GetAuctions"
	RpgService_AddItemToInventory_FullMethodName      = "/rpg.RpgService/AddItemToInventory"
	RpgService_RemoveItemFromInventory_FullMethodName = "/rpg.RpgService/RemoveItemFromInventory"
	RpgService_UploadAvatar_FullMethodName            = "/rpg.RpgService/UploadAvatar"
	RpgService_DownloadAvatar_FullMethodName          = "/rpg.RpgService/DownloadAvatar"
	RpgService_GetItems_FullMethodName                = "/rpg.RpgService/GetItems"
	RpgService_VerifyUser_FullMethodName              = "/rpg.RpgService/VerifyUser"
)

// RpgServiceClient is the client API for RpgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpgServiceClient interface {
	GetInventory(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*InventoryResponse, error)
	GetAuctions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AuctionListResponse, error)
	AddItemToInventory(ctx context.Context, in *ModifyItemRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	RemoveItemFromInventory(ctx context.Context, in *ModifyItemRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	UploadAvatar(ctx context.Context, in *UploadAvatarRequest, opts ...grpc.CallOption) (*UploadAvatarResponse, error)
	DownloadAvatar(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*DownloadAvatarResponse, error)
	GetItems(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InventoryResponse, error)
	VerifyUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type rpgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRpgServiceClient(cc grpc.ClientConnInterface) RpgServiceClient {
	return &rpgServiceClient{cc}
}

func (c *rpgServiceClient) GetInventory(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*InventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InventoryResponse)
	err := c.cc.Invoke(ctx, RpgService_GetInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpgServiceClient) GetAuctions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AuctionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuctionListResponse)
	err := c.cc.Invoke(ctx, RpgService_GetAuctions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpgServiceClient) AddItemToInventory(ctx context.Context, in *ModifyItemRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, RpgService_AddItemToInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpgServiceClient) RemoveItemFromInventory(ctx context.Context, in *ModifyItemRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, RpgService_RemoveItemFromInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpgServiceClient) UploadAvatar(ctx context.Context, in *UploadAvatarRequest, opts ...grpc.CallOption) (*UploadAvatarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadAvatarResponse)
	err := c.cc.Invoke(ctx, RpgService_UploadAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpgServiceClient) DownloadAvatar(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*DownloadAvatarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadAvatarResponse)
	err := c.cc.Invoke(ctx, RpgService_DownloadAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpgServiceClient) GetItems(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InventoryResponse)
	err := c.cc.Invoke(ctx, RpgService_GetItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpgServiceClient) VerifyUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, RpgService_VerifyUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpgServiceServer is the server API for RpgService service.
// All implementations must embed UnimplementedRpgServiceServer
// for forward compatibility.
type RpgServiceServer interface {
	GetInventory(context.Context, *UserRequest) (*InventoryResponse, error)
	GetAuctions(context.Context, *Empty) (*AuctionListResponse, error)
	AddItemToInventory(context.Context, *ModifyItemRequest) (*ActionResponse, error)
	RemoveItemFromInventory(context.Context, *ModifyItemRequest) (*ActionResponse, error)
	UploadAvatar(context.Context, *UploadAvatarRequest) (*UploadAvatarResponse, error)
	DownloadAvatar(context.Context, *UserRequest) (*DownloadAvatarResponse, error)
	GetItems(context.Context, *Empty) (*InventoryResponse, error)
	VerifyUser(context.Context, *LoginRequest) (*LoginResponse, error)
	mustEmbedUnimplementedRpgServiceServer()
}

// UnimplementedRpgServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRpgServiceServer struct{}

func (UnimplementedRpgServiceServer) GetInventory(context.Context, *UserRequest) (*InventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInventory not implemented")
}
func (UnimplementedRpgServiceServer) GetAuctions(context.Context, *Empty) (*AuctionListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuctions not implemented")
}
func (UnimplementedRpgServiceServer) AddItemToInventory(context.Context, *ModifyItemRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddItemToInventory not implemented")
}
func (UnimplementedRpgServiceServer) RemoveItemFromInventory(context.Context, *ModifyItemRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveItemFromInventory not implemented")
}
func (UnimplementedRpgServiceServer) UploadAvatar(context.Context, *UploadAvatarRequest) (*UploadAvatarResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadAvatar not implemented")
}
func (UnimplementedRpgServiceServer) DownloadAvatar(context.Context, *UserRequest) (*DownloadAvatarResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadAvatar not implemented")
}
func (UnimplementedRpgServiceServer) GetItems(context.Context, *Empty) (*InventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItems not implemented")
}
func (UnimplementedRpgServiceServer) VerifyUser(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyUser not implemented")
}
func (UnimplementedRpgServiceServer) mustEmbedUnimplementedRpgServiceServer() {}
func (UnimplementedRpgServiceServer) testEmbeddedByValue()                    {}

// UnsafeRpgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpgServiceServer will
// result in compilation errors.
type UnsafeRpgServiceServer interface {
	mustEmbedUnimplementedRpgServiceServer()
}

func RegisterRpgServiceServer(s grpc.ServiceRegistrar, srv RpgServiceServer) {
	// If the following call panics, it indicates UnimplementedRpgServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RpgService_ServiceDesc, srv)
}

func _RpgService_GetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpgServiceServer).GetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpgService_GetInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpgServiceServer).GetInventory(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpgService_GetAuctions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpgServiceServer).GetAuctions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpgService_GetAuctions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpgServiceServer).GetAuctions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpgService_AddItemToInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpgServiceServer).AddItemToInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpgService_AddItemToInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpgServiceServer).AddItemToInventory(ctx, req.(*ModifyItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpgService_RemoveItemFromInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpgServiceServer).RemoveItemFromInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpgService_RemoveItemFromInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpgServiceServer).RemoveItemFromInventory(ctx, req.(*ModifyItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpgService_UploadAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadAvatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpgServiceServer).UploadAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpgService_UploadAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpgServiceServer).UploadAvatar(ctx, req.(*UploadAvatarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpgService_DownloadAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpgServiceServer).DownloadAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpgService_DownloadAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpgServiceServer).DownloadAvatar(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpgService_GetItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpgServiceServer).GetItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpgService_GetItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpgServiceServer).GetItems(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpgService_VerifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpgServiceServer).VerifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpgService_VerifyUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpgServiceServer).VerifyUser(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RpgService_ServiceDesc is the grpc.ServiceDesc for RpgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpg.RpgService",
	HandlerType: (*RpgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInventory",
			Handler:    _RpgService_GetInventory_Handler,
		},
		{
			MethodName: "GetAuctions",
			Handler:    _RpgService_GetAuctions_Handler,
		},
		{
			MethodName: "AddItemToInventory",
			Handler:    _RpgService_AddItemToInventory_Handler,
		},
		{
			MethodName: "RemoveItemFromInventory",
			Handler:    _RpgService_RemoveItemFromInventory_Handler,
		},
		{
			MethodName: "UploadAvatar",
			Handler:    _RpgService_UploadAvatar_Handler,
		},
		{
			MethodName: "DownloadAvatar",
			Handler:    _RpgService_DownloadAvatar_Handler,
		},
		{
			MethodName: "GetItems",
			Handler:    _RpgService_GetItems_Handler,
		},
		{
			MethodName: "VerifyUser",
			Handler:    _RpgService_VerifyUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpg_system.proto",
}
