// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: rpg_system.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_rpg_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rpg_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rpg_system_proto_rawDescGZIP(), []int{0}
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_rpg_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpg_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_rpg_system_proto_rawDescGZIP(), []int{1}
}

func (x *UserRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_rpg_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpg_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_rpg_system_proto_rawDescGZIP(), []int{2}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryResponse) Reset() {
	*x = InventoryResponse{}
	mi := &file_rpg_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryResponse) ProtoMessage() {}

func (x *InventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpg_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryResponse.ProtoReflect.Descriptor instead.
func (*InventoryResponse) Descriptor() ([]byte, []int) {
	return file_rpg_system_proto_rawDescGZIP(), []int{3}
}

func (x *InventoryResponse) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type ModifyItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ItemId        int64                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyItemRequest) Reset() {
	*x = ModifyItemRequest{}
	mi := &file_rpg_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyItemRequest) ProtoMessage() {}

func (x *ModifyItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpg_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyItemRequest.ProtoReflect.Descriptor instead.
func (*ModifyItemRequest) Descriptor() ([]byte, []int) {
	return file_rpg_system_proto_rawDescGZIP(), []int{4}
}

func (x *ModifyItemRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ModifyItemRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type AuctionListResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActiveAuctions []string               `protobuf:"bytes,1,rep,name=active_auctions,json=activeAuctions,proto3" json:"active_auctions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuctionListResponse) Reset() {
	*x = AuctionListResponse{}
	mi := &file_rpg_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionListResponse) ProtoMessage() {}

func (x *AuctionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpg_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionListResponse.ProtoReflect.Descriptor instead.
func (*AuctionListResponse) Descriptor() ([]byte, []int) {
	return file_rpg_system_proto_rawDescGZIP(), []int{5}
}

func (x *AuctionListResponse) GetActiveAuctions() []string {
	if x != nil {
		return x.ActiveAuctions
	}
	return nil
}

type UploadAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ImageData     []byte                 `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // <-- NOWE POLE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAvatarRequest) Reset() {
	*x = UploadAvatarRequest{}
	mi := &file_rpg_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarRequest) ProtoMessage() {}

func (x *UploadAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpg_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarRequest.ProtoReflect.Descriptor instead.
func (*UploadAvatarRequest) Descriptor() ([]byte, []int) {
	return file_rpg_system_proto_rawDescGZIP(), []int{6}
}

func (x *UploadAvatarRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UploadAvatarRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *UploadAvatarRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type DownloadAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // <-- NOWE POLE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadAvatarResponse) Reset() {
	*x = DownloadAvatarResponse{}
	mi := &file_rpg_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadAvatarResponse) ProtoMessage() {}

func (x *DownloadAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpg_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadAvatarResponse.ProtoReflect.Descriptor instead.
func (*DownloadAvatarResponse) Descriptor() ([]byte, []int) {
	return file_rpg_system_proto_rawDescGZIP(), []int{7}
}

func (x *DownloadAvatarResponse) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *DownloadAvatarResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type UploadAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAvatarResponse) Reset() {
	*x = UploadAvatarResponse{}
	mi := &file_rpg_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarResponse) ProtoMessage() {}

func (x *UploadAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpg_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarResponse.ProtoReflect.Descriptor instead.
func (*UploadAvatarResponse) Descriptor() ([]byte, []int) {
	return file_rpg_system_proto_rawDescGZIP(), []int{8}
}

func (x *UploadAvatarResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadAvatarResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_rpg_system_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpg_system_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_rpg_system_proto_rawDescGZIP(), []int{9}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_rpg_system_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpg_system_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_rpg_system_proto_rawDescGZIP(), []int{10}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpg_system_proto protoreflect.FileDescriptor

const file_rpg_system_proto_rawDesc = "" +
	"\n" +
	"\x10rpg_system.proto\x12\x03rpg\"\a\n" +
	"\x05Empty\"#\n" +
	"\vUserRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"D\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\")\n" +
	"\x11InventoryResponse\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05items\"B\n" +
	"\x11ModifyItemRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x03R\x06itemId\">\n" +
	"\x13AuctionListResponse\x12'\n" +
	"\x0factive_auctions\x18\x01 \x03(\tR\x0eactiveAuctions\"m\n" +
	"\x13UploadAvatarRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"image_data\x18\x02 \x01(\fR\timageData\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"Z\n" +
	"\x16DownloadAvatarResponse\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"J\n" +
	"\x14UploadAvatarResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"Y\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xf1\x03\n" +
	"\n" +
	"RpgService\x128\n" +
	"\fGetInventory\x12\x10.rpg.UserRequest\x1a\x16.rpg.InventoryResponse\x123\n" +
	"\vGetAuctions\x12\n" +
	".rpg.Empty\x1a\x18.rpg.AuctionListResponse\x12A\n" +
	"\x12AddItemToInventory\x12\x16.rpg.ModifyItemRequest\x1a\x13.rpg.ActionResponse\x12F\n" +
	"\x17RemoveItemFromInventory\x12\x16.rpg.ModifyItemRequest\x1a\x13.rpg.ActionResponse\x12C\n" +
	"\fUploadAvatar\x12\x18.rpg.UploadAvatarRequest\x1a\x19.rpg.UploadAvatarResponse\x12?\n" +
	"\x0eDownloadAvatar\x12\x10.rpg.UserRequest\x1a\x1b.rpg.DownloadAvatarResponse\x12.\n" +
	"\bGetItems\x12\n" +
	".rpg.Empty\x1a\x16.rpg.InventoryResponse\x123\n" +
	"\n" +
	"VerifyUser\x12\x11.rpg.LoginRequest\x1a\x12.rpg.LoginResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_rpg_system_proto_rawDescOnce sync.Once
	file_rpg_system_proto_rawDescData []byte
)

func file_rpg_system_proto_rawDescGZIP() []byte {
	file_rpg_system_proto_rawDescOnce.Do(func() {
		file_rpg_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpg_system_proto_rawDesc), len(file_rpg_system_proto_rawDesc)))
	})
	return file_rpg_system_proto_rawDescData
}

var file_rpg_system_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_rpg_system_proto_goTypes = []any{
	(*Empty)(nil),                  // 0: rpg.Empty
	(*UserRequest)(nil),            // 1: rpg.UserRequest
	(*ActionResponse)(nil),         // 2: rpg.ActionResponse
	(*InventoryResponse)(nil),      // 3: rpg.InventoryResponse
	(*ModifyItemRequest)(nil),      // 4: rpg.ModifyItemRequest
	(*AuctionListResponse)(nil),    // 5: rpg.AuctionListResponse
	(*UploadAvatarRequest)(nil),    // 6: rpg.UploadAvatarRequest
	(*DownloadAvatarResponse)(nil), // 7: rpg.DownloadAvatarResponse
	(*UploadAvatarResponse)(nil),   // 8: rpg.UploadAvatarResponse
	(*LoginRequest)(nil),           // 9: rpg.LoginRequest
	(*LoginResponse)(nil),          // 10: rpg.LoginResponse
}
var file_rpg_system_proto_depIdxs = []int32{
	1,  // 0: rpg.RpgService.GetInventory:input_type -> rpg.UserRequest
	0,  // 1: rpg.RpgService.GetAuctions:input_type -> rpg.Empty
	4,  // 2: rpg.RpgService.AddItemToInventory:input_type -> rpg.ModifyItemRequest
	4,  // 3: rpg.RpgService.RemoveItemFromInventory:input_type -> rpg.ModifyItemRequest
	6,  // 4: rpg.RpgService.UploadAvatar:input_type -> rpg.UploadAvatarRequest
	1,  // 5: rpg.RpgService.DownloadAvatar:input_type -> rpg.UserRequest
	0,  // 6: rpg.RpgService.GetItems:input_type -> rpg.Empty
	9,  // 7: rpg.RpgService.VerifyUser:input_type -> rpg.LoginRequest
	3,  // 8: rpg.RpgService.GetInventory:output_type -> rpg.InventoryResponse
	5,  // 9: rpg.RpgService.GetAuctions:output_type -> rpg.AuctionListResponse
	2,  // 10: rpg.RpgService.AddItemToInventory:output_type -> rpg.ActionResponse
	2,  // 11: rpg.RpgService.RemoveItemFromInventory:output_type -> rpg.ActionResponse
	8,  // 12: rpg.RpgService.UploadAvatar:output_type -> rpg.UploadAvatarResponse
	7,  // 13: rpg.RpgService.DownloadAvatar:output_type -> rpg.DownloadAvatarResponse
	3,  // 14: rpg.RpgService.GetItems:output_type -> rpg.InventoryResponse
	10, // 15: rpg.RpgService.VerifyUser:output_type -> rpg.LoginResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_rpg_system_proto_init() }
func file_rpg_system_proto_init() {
	if File_rpg_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpg_system_proto_rawDesc), len(file_rpg_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpg_system_proto_goTypes,
		DependencyIndexes: file_rpg_system_proto_depIdxs,
		MessageInfos:      file_rpg_system_proto_msgTypes,
	}.Build()
	File_rpg_system_proto = out.File
	file_rpg_system_proto_goTypes = nil
	file_rpg_system_proto_depIdxs = nil
}
